import { expect, test, type Page } from '@playwright/test'
import { ACCOUNT, expectNoA11yViolations, settle, signInFully } from '../support/session'

type Mock = { expireReauth(): void; setDegraded(v: boolean): void; setLiveReadonly(v: boolean): void }
const mock = <T>(page: Page, fn: (m: Mock) => T) => page.evaluate(`(${fn.toString()})(window.__boMock)`)

test.describe('abonelikler', () => {
  test.beforeEach(async ({ page }) => signInFully(page))

  test('liste: h1, axe 0, filtre ve boş durum', async ({ page }) => {
    await page.goto('/abonelikler')
    await expect(page.getByRole('heading', { level: 1, name: 'Abonelikler' })).toBeVisible()
    await settle(page)
    await expect(page.getByTestId('sub-101')).toBeVisible()
    await expect(page.getByText('kartsız').first()).toBeVisible()
    await expect(page.getByText('VİSA •••• 4242')).toBeVisible()
    await expect(page.getByRole('tab', { name: /Abonelikler/ })).toContainText(/\d/)
    await expect(page.getByRole('link', { name: /aboneliği ayrıntı/ }).first()).toBeVisible()
    await expectNoA11yViolations(page)

    await page.getByTestId('status-filter').click()
    await page.getByRole('option', { name: 'Süresi doldu' }).click()
    await settle(page)
    await expect(page.getByText('Filtreye uyan abonelik yok')).toBeVisible()
    await page.getByRole('button', { name: 'Filtreleri temizle' }).click()
    await settle(page)
    await expect(page.getByTestId('sub-101')).toBeVisible()
  })

  test('gelir metrikleri: tahmini etiketi, MRR, axe 0', async ({ page }) => {
    await page.goto('/abonelikler?sekme=gelir')
    await settle(page)
    await expect(page.getByText('Liste fiyatından tahmini').first()).toBeVisible()
    await expect(page.getByTestId('mrr')).toContainText('₺')
    await expect(page.getByText('Kayıp yaklaşık')).toBeVisible()
    await page.locator('[data-value="7d"]').click()
    await settle(page)
    await expectNoA11yViolations(page)
  })

  test('detay: özet, olaylar, uygunsuz eylem devre dışı, 404', async ({ page }) => {
    await page.goto('/abonelikler/101')
    await expect(page.getByRole('heading', { level: 1, name: /Lale Ev Tekstil/ })).toBeVisible()
    await settle(page)
    // Sekmeli detay: Özet (varsayılan) · Olaylar (sayı) · Eylemler; müşteriye gitme bağlantısı başlıkta.
    await expect(page.getByRole('tab', { name: /Özet/ })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByRole('tab', { name: /Olaylar/ })).toContainText(/\d/)
    await page.getByRole('tab', { name: /Olaylar/ }).click()
    await expect(page).toHaveURL(/sekme=olaylar/)
    await expect(page.getByRole('heading', { name: 'Faturalama olayları' })).toBeVisible()
    await page.getByRole('tab', { name: 'Eylemler' }).click()
    await expect(page).toHaveURL(/sekme=eylemler/)
    await expect(page.getByTestId('extend-trial')).toBeDisabled()
    await expect(page.getByText('Yalnız deneme sürecindeki ya da denemesi bitmiş (askıdaki, kartsız) abonelik uzatılabilir.')).toBeVisible()
    await expect(page.getByTestId('tenant-link')).toHaveAttribute('href', '/musteriler/101')
    await expectNoA11yViolations(page)
    await page.goto('/abonelikler/999')
    await expect(page.getByText('Abonelik bulunamadı')).toBeVisible()
  })

  test('denemeyi uzat: step-up + gerekçe → toast', async ({ page }) => {
    await page.goto('/abonelikler/103?sekme=eylemler')
    await settle(page)
    await mock(page, (m) => m.expireReauth())
    await page.getByTestId('extend-trial').click()
    const dialog = page.getByRole('dialog', { name: 'Deneme süresi uzatılsın mı?' })
    await dialog.getByTestId('extend-days').locator('input').fill('10')
    await dialog.getByLabel('Gerekçe').fill('Müşteri talebi: kurulum gecikti')
    await dialog.getByRole('button', { name: 'Denemeyi uzat' }).click()
    const reauth = page.getByRole('dialog', { name: 'Kimliğinizi yeniden doğrulayın' })
    await expect(reauth).toBeVisible()
    await reauth.getByLabel('Parola').fill(ACCOUNT.password)
    await reauth.getByLabel('Doğrulama kodu').fill('135790')
    await reauth.getByRole('button', { name: 'Doğrula ve devam et' }).click()
    await expect(page.getByText(/Deneme 10 gün uzatıldı/)).toBeVisible()
  })

  test('K40 iptal: kartsız abonelik doğrudan iptal (salt-okumada da); kartlıda salt-okuma 423 diyalogda', async ({ page }) => {
    await page.goto('/abonelikler/103?sekme=eylemler')
    await settle(page)
    await mock(page, (m) => m.setLiveReadonly(true))
    await page.getByTestId('cancel-sub').click()
    const dialog = page.getByRole('dialog', { name: 'Abonelik iptal edilsin mi?' })
    await expect(dialog.getByTestId('cancel-local')).toBeVisible()
    await expect(dialog.getByRole('radiogroup', { name: 'İptal zamanı' })).toHaveCount(0)
    await dialog.getByLabel('Gerekçe').fill('Test: kartsız deneme iptali')
    await dialog.getByRole('button', { name: 'Aboneliği iptal et' }).click()
    await expect(page.getByText('Abonelik doğrudan (sağlayıcı kaydı yok) iptal edildi.')).toBeVisible()

    await page.goto('/abonelikler/101?sekme=eylemler')
    await settle(page)
    await mock(page, (m) => m.setLiveReadonly(true))
    await page.getByTestId('cancel-sub').click()
    const d2 = page.getByRole('dialog', { name: 'Abonelik iptal edilsin mi?' })
    await d2.getByLabel('Gerekçe').fill('Test: kartlı abonelik iptali')
    await d2.getByRole('button', { name: 'Aboneliği iptal et' }).click()
    await expect(d2.locator('.v-input__details')).toContainText('salt-okuma')
  })

  test('K40 uzatma sınırı: kullanılan/kalan gösterilir, kalandan fazlası girilemez', async ({ page }) => {
    await page.goto('/abonelikler/103')
    await settle(page)
    await expect(page.getByTestId('extension-usage')).toContainText('45 / 60 gün')
    await page.getByRole('tab', { name: 'Eylemler' }).click()
    await page.getByTestId('extend-trial').click()
    const dialog = page.getByRole('dialog', { name: 'Deneme süresi uzatılsın mı?' })
    await dialog.getByTestId('extend-days').locator('input').fill('16')
    await expect(dialog.getByText('Gün 1 ile 15 arasında tam sayı olmalı.')).toBeVisible()
    await dialog.getByLabel('Gerekçe').fill('Müşteri talebi: kurulum gecikti')
    await expect(dialog.getByRole('button', { name: 'Denemeyi uzat' })).toBeDisabled()
    await expectNoA11yViolations(page)
  })

  test('K40 yeniden aç: askıdaki kartsız deneme uzatmayla yeniden açılır', async ({ page }) => {
    await page.goto('/abonelikler/109?sekme=eylemler')
    await settle(page)
    await expect(page.getByTestId('extend-trial')).toHaveText(/Denemeyi yeniden aç/)
    await page.getByTestId('extend-trial').click()
    const dialog = page.getByRole('dialog', { name: 'Deneme yeniden açılsın mı?' })
    await dialog.getByTestId('extend-days').locator('input').fill('14')
    await dialog.getByLabel('Gerekçe').fill('Müşteri ödeme yöntemini ekleyecek')
    await dialog.getByRole('button', { name: 'Denemeyi yeniden aç' }).click()
    await expect(page.getByText(/Deneme yeniden açıldı \(14 gün\).*Kalan uzatma hakkı 46 gün/)).toBeVisible()
  })

  test('plan değiştir: aynı plan seçilemez, başarıda toast', async ({ page }) => {
    await page.goto('/abonelikler/101?sekme=eylemler')
    await settle(page)
    await page.getByTestId('change-plan').click()
    const dialog = page.getByRole('dialog', { name: 'Plan değiştirilsin mi?' })
    await dialog.getByLabel('Gerekçe').fill('Müşteri üst plana geçmek istedi')
    await expect(dialog.getByRole('button', { name: 'Planı değiştir' })).toBeDisabled()
    await dialog.getByTestId('target-plan').click()
    await page.getByRole('option', { name: /Başlangıç/ }).click()
    await dialog.getByRole('button', { name: 'Planı değiştir' }).click()
    await expect(page.getByText('Plan Başlangıç olarak değiştirildi.')).toBeVisible()
  })
})
