// bo-next: Bildirimler ve duyurular (NB7/NB8). Sahte /admin-api; görsel taban YOK (Windows'ta üretilir).
// Sahte durum sayfa yenilemesinde sıfırlanır: akışlar SPA içi gezinmeyle sürer.
import { expect, test, type Page } from '@playwright/test'
import { expectNoA11yViolations, settle, signInFully } from '../support/session'

type Mock = { expireReauth(): void; setLiveReadonly(v: boolean): void; setNotifyEmail(v: boolean): void }
const mock = (page: Page, fn: (m: Mock) => void) => page.evaluate(`(${fn.toString()})(window.__boMock)`)
const REASON = 'Destek kaydı DK-örnek: e2e gerekçesi'

async function stepUp(page: Page) {
  const dialog = page.getByRole('dialog', { name: 'Kimliğinizi yeniden doğrulayın' })
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Parola').fill('ornek-parola')
  await dialog.getByLabel('Doğrulama kodu').fill('222222')
  await dialog.getByRole('button', { name: 'Doğrula ve devam et' }).click()
}
async function openFromMenu(page: Page, ...labels: string[]) {
  if (page.viewportSize()!.width < 960) await page.getByRole('button', { name: 'Menüyü aç' }).click()
  const nav = page.getByRole('navigation', { name: 'Yönetim ekranları' })
  for (const label of labels) {
    const btn = nav.getByRole('button', { name: new RegExp(`^${label}(\\s|$)`) })
    if ((await btn.getAttribute('aria-expanded')) !== 'true') await btn.click()
  }
}
async function noHorizontalScroll(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
}

test.describe('bildirimler ve duyurular', () => {
  test.beforeEach(async ({ page }) => signInFully(page))

  test('duyurular: menüden açılır, yayındaki özet, filtre, axe 0', async ({ page }) => {
    await openFromMenu(page, 'Bildirimler ve duyurular', 'Duyurular')
    await expect(page).toHaveURL(/\/sistem\/duyurular$/)
    await expect(page.getByRole('heading', { level: 1, name: 'Duyurular' })).toBeVisible()
    await settle(page)
    await expect(page.getByTestId('live-summary')).toContainText('Trendyol sipariş eşitlemesinde gecikme')
    await expectNoA11yViolations(page)
    await page.locator('[data-status="draft"]').click()
    await settle(page)
    await expect(page.getByRole('link', { name: 'Yeni: toplu fiyat güncelleme' })).toBeVisible()
    await expect(page.getByRole('link', { name: /Trendyol sipariş/ })).toHaveCount(0)
    await noHorizontalScroll(page)
  })

  test('oluştur → önizleme (bant/uygulama/e-posta sandbox) → taslak → zamanla (e-posta onayı zorunlu)', async ({ page }, info) => {
    test.skip(info.project.name === 'chromium-mobile', 'akış masaüstünde; mobil yerleşim ayrı testte')
    test.setTimeout(150_000)
    await page.goto('/sistem/duyurular')
    await page.getByTestId('new-announcement').click()
    await expect(page.getByRole('heading', { level: 1, name: 'Yeni duyuru' })).toBeVisible()
    await page.locator('[data-kind="maintenance"]').click()
    await page.getByTestId('title-tr').locator('input').fill('Planlı bakım: arama altyapısı')
    await page.getByTestId('body-tr').locator('textarea').first().fill('Bakım süresince ürün araması yavaşlayabilir.')
    await page.locator('[data-target="plans"]').click()
    await page.getByRole('checkbox', { name: 'Büyüme' }).check()
    await page.getByTestId('ch-email').locator('input').check()
    await expect(page.getByTestId('ch-inapp').locator('input')).toBeChecked()
    // Canlı önizleme: bant kapatılamaz (bakım), e-posta sandbox iframe'de.
    await expect(page.getByTestId('banner-preview')).toContainText('Planlı bakım: arama altyapısı')
    await expect(page.getByTestId('banner-preview')).toContainText('Bant kapatılamaz')
    await page.getByRole('tab', { name: 'E-posta' }).click()
    const frame = page.getByTestId('email-frame')
    await expect(frame).toHaveAttribute('sandbox', '')
    await expect(page.frameLocator('[data-testid="email-frame"]').locator('h1')).toContainText('Planlı bakım')
    await expectNoA11yViolations(page)

    await page.getByTestId('save').click()
    const save = page.getByRole('dialog', { name: 'Taslak oluşturulsun mu?' })
    await save.getByLabel('Gerekçe').fill(REASON)
    await save.getByRole('button', { name: 'Gerekçeyle kaydet' }).click()
    await expect(page.getByText('Taslak oluşturuldu. Yayına almak için zamanlayın.')).toBeVisible()
    await expect(page).toHaveURL(/\/sistem\/duyurular\/[a-f0-9]{24}$/)
    await expect(page.getByTestId('ann-status')).toContainText('Taslak')
    await expect(page.getByTestId('target')).toHaveText('Plan: Büyüme')

    await mock(page, (m) => m.expireReauth())
    await page.getByTestId('schedule').click()
    const sch = page.getByRole('dialog', { name: /Duyuru (zamanlansın|şimdi yayınlansın) mı\?/ })
    await sch.getByLabel('Gerekçe').fill(REASON)
    const confirm = sch.getByRole('button', { name: /Gerekçeyle (zamanla|yayınla)/ })
    await expect(confirm).toBeDisabled()
    await sch.getByTestId('email-consent').locator('input').check()
    await confirm.click()
    await stepUp(page)
    await expect(page.getByTestId('ann-status')).toContainText(/Zamanlandı|Yayında/)
    await expect(page.getByTestId('edit')).toHaveCount(0)
  })

  test('yayındaki olay duyurusunu iptal: yıkıcı diyalog, gerekçe, durum', async ({ page }) => {
    await page.goto('/sistem/duyurular')
    await settle(page)
    await page.getByRole('link', { name: 'Trendyol sipariş eşitlemesinde gecikme' }).click()
    await expect(page.getByTestId('ann-status')).toContainText('Yayında')
    await expectNoA11yViolations(page)
    await page.getByTestId('cancel').click()
    const d = page.getByRole('dialog', { name: 'Duyuru iptal edilsin mi?' })
    await expect(d).toContainText('Bant müşteri ekranlarından hemen kalkar.')
    await d.getByLabel('Gerekçe').fill(REASON)
    await d.getByRole('button', { name: 'Duyuruyu iptal et' }).click()
    await expect(page.getByTestId('ann-status')).toContainText('İptal edildi')
  })

  test('teslim günlüğü: istatistik, kalıcı hatalar, yeniden dene (step-up) ve salt-okuma 423, axe 0', async ({ page }) => {
    await openFromMenu(page, 'Bildirimler ve duyurular', 'Teslim günlüğü')
    await expect(page.getByRole('heading', { level: 1, name: 'Teslim günlüğü' })).toBeVisible()
    await settle(page)
    await expect(page.getByTestId('delivery-kpis')).toContainText('Kalıcı hata')
    await expectNoA11yViolations(page)
    await page.locator('[data-status="dead"]').click()
    await settle(page)
    await expect(page).toHaveURL(/durum=dead/)
    await mock(page, (m) => m.setLiveReadonly(true))
    await page.getByTestId('retry').first().click()
    const d = page.getByRole('dialog', { name: 'Teslim yeniden denensin mi?' })
    await d.getByLabel('Gerekçe').fill(REASON)
    await d.getByRole('button', { name: 'Yeniden dene' }).click()
    await expect(d.locator('.v-input__details')).toContainText('salt-okuma')
    await mock(page, (m) => m.setLiveReadonly(false))
    await mock(page, (m) => m.expireReauth())
    await d.getByRole('button', { name: 'Yeniden dene' }).click()
    await stepUp(page)
    await expect(page.getByText(/teslimi yeniden kuyruğa alındı/)).toBeVisible()
    await noHorizontalScroll(page)
  })

  test('müşteri bildirim geçmişi: müşteri detayından açılır, yalnız meta veri, olay → teslimler; boş durum', async ({ page }) => {
    await page.goto('/musteriler/101?sekme=yasam-dongusu')
    await page.getByTestId('notification-history').click()
    await expect(page.getByRole('heading', { level: 1, name: 'Müşteri bildirim geçmişi' })).toBeVisible()
    await expect(page).toHaveURL(/tid=101/)
    await settle(page)
    await expect(page.getByText('Her görüntüleme hassas okuma olarak denetime yazılır.')).toBeVisible()
    await expectNoA11yViolations(page)
    await page.getByRole('link', { name: /olayının e-posta teslimlerini aç/ }).first().click()
    await expect(page).toHaveURL(/\/bildirimler\/teslimler\?olay=[a-f0-9]{24}/)
    await expect(page.getByText(/Olay [a-f0-9]{24} teslimleri/)).toBeVisible()
    await page.goto('/bildirimler/musteri-gecmisi')
    await page.getByTestId('tid-input').locator('input').fill('102')
    await page.getByTestId('show-history').click()
    await expect(page.getByText('Bildirim geçmişi yok')).toBeVisible()
  })

  test('katalog: şablon önizleme (uygulama içi + e-posta), test e-postası ve 503 iletisi', async ({ page }) => {
    await page.goto('/bildirimler/katalog')
    await expect(page.getByRole('heading', { level: 1, name: 'Olay kataloğu' })).toBeVisible()
    await settle(page)
    await page.locator('[data-code="ORDER_SYNC_FAILED"]').click()
    await expect(page.getByTestId('template-preview')).toContainText('UPSTREAM_TIMEOUT')
    await page.locator('[data-channel="email"]').click()
    await expect(page.frameLocator('[data-testid="email-frame"]').locator('h1')).toContainText('Sipariş eşitleme başarısız')
    await expectNoA11yViolations(page)
    await page.getByTestId('test-email').click()
    const d = page.getByRole('dialog', { name: 'Test e-postası gönderilsin mi?' })
    await d.getByLabel('Gerekçe').fill(REASON)
    await mock(page, (m) => m.setNotifyEmail(false))
    await d.getByRole('button', { name: 'Gerekçeyle gönder' }).click()
    await expect(d.locator('.v-input__details')).toContainText('E-posta gönderimi şu an kapalı')
    await mock(page, (m) => m.setNotifyEmail(true))
    await d.getByRole('button', { name: 'Gerekçeyle gönder' }).click()
    await expect(page.getByText('Test e-postası kendi adresinize gönderildi.')).toBeVisible()
  })

  test('platform uyarıları: etkinler, gölge bilgisi, sustur ve kaldır, axe 0', async ({ page }) => {
    await page.goto('/bildirimler/uyarilar')
    await expect(page.getByRole('heading', { level: 1, name: 'Platform uyarıları' })).toBeVisible()
    await settle(page)
    await expect(page.getByText('Gölge modda uyarılar var')).toBeVisible()
    await expect(page.getByTestId('muted-chip')).toHaveCount(1)
    await expectNoA11yViolations(page)
    await page.getByTestId('mute').first().click()
    const d = page.getByRole('dialog', { name: 'Uyarı susturulsun mu?' })
    await d.getByLabel('Gerekçe').fill(REASON)
    await d.getByRole('button', { name: 'Gerekçeyle sustur' }).click()
    await expect(page.getByText(/tarihine kadar susturuldu/)).toBeVisible()
    await expect(page.getByTestId('muted-chip')).toHaveCount(2)
    await page.getByTestId('unmute').first().click()
    const u = page.getByRole('dialog', { name: 'Susturma kaldırılsın mı?' })
    await u.getByLabel('Gerekçe').fill(REASON)
    await u.getByRole('button', { name: 'Susturmayı kaldır' }).click()
    await expect(page.getByText('Susturma kaldırıldı.')).toBeVisible()
    await noHorizontalScroll(page)
  })

  test('düzenleyici mobil: tek sütun, yatay kaydırma yok, axe 0', async ({ page }, info) => {
    test.skip(info.project.name !== 'chromium-mobile')
    await page.goto('/sistem/duyurular/yeni')
    await expect(page.getByRole('heading', { level: 1, name: 'Yeni duyuru' })).toBeVisible()
    await page.getByTestId('title-tr').locator('input').fill('Mobil deneme')
    await page.getByTestId('body-tr').locator('textarea').first().fill('Kısa metin.')
    await expect(page.getByTestId('banner-preview')).toContainText('Mobil deneme')
    await noHorizontalScroll(page)
    await expectNoA11yViolations(page)
  })
})
