// ADR-0029 Karar 1: EN sablonlari (tr.ts ile ayni anahtar kumesi; test denetler).
export const EN: Record<string, { title: string; body: string }> = {
    ORDER_SYNC_WINDOW_OVERFLOW: { title: 'Order sync window exceeded', body: 'The order window was exceeded for {integ} ({reason}); missing orders will be fetched on the next run.' },
    ORDER_SYNC_FAILED: { title: 'Order sync failed', body: 'Could not fetch {integ} orders (error code: {errorCode}). Support code: {corrId}.' },
    ORDER_SYNC_LAGGING: { title: 'Order sync is lagging', body: '{integ} order sync is about {lagMinutes} minutes behind.' },
    STOCK_OVERSOLD: { title: 'Stock oversold', body: 'Line {lineId} on {integ} was sold beyond available stock. Order: {orderId}.' },
    STOCK_UNMAPPED_LINE: { title: 'Unmapped order line', body: 'Line {lineId} on {integ} did not match a product; stock could not be deducted.' },
    STOCK_REALLOCATED: { title: 'Stock reallocated', body: 'Stock was reallocated for line {lineId}. Order: {orderId}.' },
    STOCK_LINE_AUTO_CANCELLED: { title: 'Order line auto-cancelled', body: 'Line {lineId} was automatically cancelled due to insufficient stock. Order: {orderId}.' },
    STOCK_COMPENSATION_MANUAL: { title: 'Manual action required', body: 'Line {lineId} could not be resolved automatically ({reason}). Order: {orderId}.' },
    STOCK_OVERSOLD_UNRESOLVED: { title: 'Unresolved oversold lines', body: '{count} lines are still waiting to be resolved.' },
    STOCK_LOW: { title: 'Low stock', body: 'Available stock for {sku} dropped to {available} (threshold: {threshold}).' },
    INTEGRATION_AUTH_FAILED: { title: 'Integration authentication failed', body: '{integ} credentials were rejected; the integration is not working. Update the credentials.' },
    INTEGRATION_CIRCUIT_OPEN: { title: 'Integration paused', body: 'Requests to {integ} were paused temporarily after repeated errors.' },
    INTEGRATION_ERROR_RATE_HIGH: { title: 'High integration error rate', body: 'The error rate for {integ} is {ratePercent}%.' },
    INTEGRATION_CHANGE_NOTICE: { title: 'Integration change notice', body: 'An API change was detected for {integ} (record: {findingId}).' },
    CATALOG_BATCH_SUBMITTED: { title: 'Batch submitted', body: '{itemCount} records were submitted to {integ} (job: {batchId}).' },
    CATALOG_BATCH_FAILED: { title: 'Batch failed', body: 'The {integ} batch could not be completed (error code: {errorCode}). Support code: {corrId}.' },
    BUYBOX_LOST: { title: 'Buybox lost', body: 'On {integ}, the buybox for barcode {barcode} moved to another seller (rank: {buyboxOrder}, buybox price: {buyboxPrice} TRY).' },
    PRICE_RULE_PAUSED: { title: 'Pricing rule paused', body: 'A competition pricing rule on {integ} was paused (reason: {reason}). Review and save the rule again.' },
    CATALOG_IMPORT_COMPLETED: { title: 'Import completed', body: 'The {integ} import completed ({itemCount} records).' },
    CATALOG_IMPORT_FAILED: { title: 'Import failed', body: 'The {integ} import failed (error code: {errorCode}). Support code: {corrId}.' },
    CATALOG_EXPORT_ERRORS_DIGEST: { title: 'Transfer errors', body: '{failedCount} transfers to {integ} failed.' },
    FINANCE_RECONCILIATION_MISMATCH: { title: 'Reconciliation mismatch', body: 'A reconciliation mismatch was found in {mismatchCount} items.' },
    BILLING_TRIAL_ENDING: { title: 'Your trial is ending', body: 'Your trial ends on {trialEnd} ({daysLeft} days left).' },
    BILLING_TRIAL_ENDED: { title: 'Your trial has ended', body: 'Your trial ended on {trialEnd}. Choose a plan to continue.' },
    BILLING_SUSPENSION_WARNING: { title: 'Your account will be suspended', body: 'If payment is not received, your account will be suspended on {suspendAt} ({daysLeft} days left).' },
    BILLING_SUSPENDED: { title: 'Your account is suspended', body: 'Your account was suspended on {suspendAt}. Complete the payment to reactivate it.' },
    BILLING_PAYMENT_FAILED: { title: 'Payment failed', body: 'Payment for invoice {invoiceId} failed (attempt {attempt}).' },
    SECURITY_PASSWORD_CHANGED: { title: 'Your password was changed', body: 'Your account password was changed on {passwordChangedAt}. If this was not you, contact your administrator immediately.' },
    SECURITY_SUPPORT_ACCESS_STARTED: { title: 'Support access started', body: 'A support session started viewing your account in read-only mode (session: {impSessionId}).' },
    SECURITY_MEMBER_ROLE_CHANGED: { title: 'Member role changed', body: 'A member role was changed to "{newRole}" (record: {auditId}).' },
    SECURITY_OWNERSHIP_TRANSFERRED: { title: 'Account ownership transferred', body: 'Account ownership was transferred (record: {transferId}).' },
    SECURITY_MEMBER_SUSPENDED: { title: 'Member suspended', body: 'A member was suspended and their sessions were ended (user: {targetUserId}).' },
    SECURITY_OWNERSHIP_TRANSFER_REQUESTED: { title: 'Ownership transfer request', body: 'Account ownership is being transferred to you. The acceptance link was sent to your email (valid until {expiresAt}).' },
    SECURITY_MCP_CONNECTED: { title: 'An AI app was connected', body: '"{clientName}" ({redirectHost}) was connected to your account as an AI app and can read store data. If this was not you, disconnect it right away under Account > Connected apps.' },
    SYSTEM_MCP_APPROVAL_PENDING: { title: 'An AI action awaits your approval', body: '"{clientName}" proposes an action: {title}. Nothing happens until you approve it; review the details and approve or reject within 10 minutes.' },
    SYSTEM_ANNOUNCEMENT: { title: 'Announcement', body: 'A new announcement was published. Open it for details.' },
    PLATFORM_ALERT_FIRING: { title: 'Platform alert', body: 'Rule {ruleId} fired (alert: {alertId}).' },
    PLATFORM_ALERT_RESOLVED: { title: 'Platform alert resolved', body: 'Rule {ruleId} returned to normal (alert: {alertId}).' },
    PLATFORM_ALERT_DIGEST: { title: 'Platform alert digest', body: '{newAlertCount} new alerts were raised.' },
    PLATFORM_DELIVERY_DEAD_LETTERS: { title: 'Undeliverable notifications', body: '{deadCount} deliveries failed permanently in the last hour.' },
    PLATFORM_COMPLIANCE_FINDING: { title: 'Compliance finding', body: 'A new finding exists for {integ} (record: {findingId}).' },
};
