// ADR-0029 Karar 1: TR sablonlari. Anahtar = katalog kodu; {param} yer tutuculari render.ts ile doldurulur.
// Yalniz katalog params'i kullanilir; ham hata metni / PII YOK.
export const TR: Record<string, { title: string; body: string }> = {
    ORDER_SYNC_WINDOW_OVERFLOW: { title: 'Sipariş eşitleme penceresi aşıldı', body: '{integ} entegrasyonunda sipariş penceresi aşıldı ({reason}); eksik siparişler sonraki turda alınacak.' },
    ORDER_SYNC_FAILED: { title: 'Sipariş eşitleme başarısız', body: '{integ} siparişleri alınamadı (hata kodu: {errorCode}). Destek kodu: {corrId}.' },
    ORDER_SYNC_LAGGING: { title: 'Sipariş eşitleme gecikiyor', body: '{integ} sipariş eşitlemesi yaklaşık {lagMinutes} dakika geride.' },
    STOCK_OVERSOLD: { title: 'Stok aşırı satıldı', body: '{integ} kanalında {lineId} satırı stoktan fazla satıldı. Sipariş: {orderId}.' },
    STOCK_UNMAPPED_LINE: { title: 'Eşleşmemiş sipariş satırı', body: '{integ} kanalında {lineId} satırı bir ürünle eşleşmedi; stok düşülemedi.' },
    STOCK_REALLOCATED: { title: 'Stok yeniden ayrıldı', body: '{lineId} satırı için stok yeniden ayrıldı. Sipariş: {orderId}.' },
    STOCK_LINE_AUTO_CANCELLED: { title: 'Sipariş satırı otomatik iptal edildi', body: '{lineId} satırı stok yetersizliği nedeniyle otomatik iptal edildi. Sipariş: {orderId}.' },
    STOCK_COMPENSATION_MANUAL: { title: 'Elle müdahale gerekiyor', body: '{lineId} satırı otomatik çözülemedi ({reason}). Sipariş: {orderId}.' },
    STOCK_OVERSOLD_UNRESOLVED: { title: 'Çözülmemiş aşırı satış var', body: '{count} satır hâlâ çözülmeyi bekliyor.' },
    STOCK_LOW: { title: 'Stok azaldı', body: '{sku} için kullanılabilir stok {available} adede düştü (eşik: {threshold}).' },
    INTEGRATION_AUTH_FAILED: { title: 'Entegrasyon kimlik doğrulaması başarısız', body: '{integ} kimlik bilgileri reddedildi; entegrasyon çalışmıyor. Bilgileri güncelleyin.' },
    INTEGRATION_CIRCUIT_OPEN: { title: 'Entegrasyon geçici olarak durduruldu', body: '{integ} art arda hata verdiği için istekler geçici durduruldu.' },
    INTEGRATION_ERROR_RATE_HIGH: { title: 'Entegrasyon hata oranı yüksek', body: '{integ} entegrasyonunda hata oranı %{ratePercent}.' },
    INTEGRATION_CHANGE_NOTICE: { title: 'Entegrasyon değişiklik bildirimi', body: '{integ} için bir API değişikliği tespit edildi (kayıt: {findingId}).' },
    CATALOG_BATCH_SUBMITTED: { title: 'Toplu işlem gönderildi', body: '{integ} için {itemCount} kayıt gönderildi (iş: {batchId}).' },
    CATALOG_BATCH_FAILED: { title: 'Toplu işlem başarısız', body: '{integ} toplu işlemi tamamlanamadı (hata kodu: {errorCode}). Destek kodu: {corrId}.' },
    CATALOG_IMPORT_COMPLETED: { title: 'İçe aktarma tamamlandı', body: '{integ} içe aktarması tamamlandı ({itemCount} kayıt).' },
    CATALOG_IMPORT_FAILED: { title: 'İçe aktarma başarısız', body: '{integ} içe aktarması başarısız oldu (hata kodu: {errorCode}). Destek kodu: {corrId}.' },
    CATALOG_EXPORT_ERRORS_DIGEST: { title: 'Aktarım hataları', body: '{integ} için {failedCount} aktarım başarısız oldu.' },
    FINANCE_RECONCILIATION_MISMATCH: { title: 'Mutabakat farkı', body: '{mismatchCount} kalemde mutabakat farkı bulundu.' },
    BILLING_TRIAL_ENDING: { title: 'Deneme süreniz bitiyor', body: 'Deneme süreniz {trialEnd} tarihinde bitiyor ({daysLeft} gün kaldı).' },
    BILLING_TRIAL_ENDED: { title: 'Deneme süreniz bitti', body: 'Deneme süreniz {trialEnd} tarihinde sona erdi. Devam etmek için bir plan seçin.' },
    BILLING_SUSPENSION_WARNING: { title: 'Hesabınız askıya alınacak', body: 'Ödeme alınamazsa hesabınız {suspendAt} tarihinde askıya alınacak ({daysLeft} gün kaldı).' },
    BILLING_SUSPENDED: { title: 'Hesabınız askıya alındı', body: 'Hesabınız {suspendAt} tarihinde askıya alındı. Ödemeyi tamamlayarak yeniden etkinleştirin.' },
    BILLING_PAYMENT_FAILED: { title: 'Ödeme alınamadı', body: '{invoiceId} numaralı fatura için ödeme alınamadı (deneme {attempt}).' },
    SECURITY_PASSWORD_CHANGED: { title: 'Parolanız değiştirildi', body: 'Hesap parolanız {passwordChangedAt} tarihinde değiştirildi. Siz yapmadıysanız hemen yöneticinize başvurun.' },
    SECURITY_SUPPORT_ACCESS_STARTED: { title: 'Destek erişimi başladı', body: 'Bir destek oturumu hesabınızı salt okunur görüntülemeye başladı (oturum: {impSessionId}).' },
    SECURITY_MEMBER_ROLE_CHANGED: { title: 'Üye rolü değiştirildi', body: 'Bir üyenin rolü "{newRole}" olarak değiştirildi (kayıt: {auditId}).' },
    SECURITY_OWNERSHIP_TRANSFERRED: { title: 'Hesap sahipliği devredildi', body: 'Hesap sahipliği devredildi (kayıt: {transferId}).' },
    SECURITY_MEMBER_SUSPENDED: { title: 'Üye askıya alındı', body: 'Bir üye askıya alındı; oturumları kapatıldı (kullanıcı: {targetUserId}).' },
    SECURITY_OWNERSHIP_TRANSFER_REQUESTED: { title: 'Sahiplik devri talebi', body: 'Hesap sahipliği size devredilmek isteniyor. Kabul bağlantısı e-postanıza gönderildi ({expiresAt} tarihine kadar geçerli).' },
    SECURITY_MCP_CONNECTED: { title: 'Yapay zekâ uygulaması bağlandı', body: '"{clientName}" ({redirectHost}) hesabınıza yapay zekâ uygulaması olarak bağlandı ve mağaza verilerinizi okuyabilir. Siz yapmadıysanız Hesap > Bağlı uygulamalar bölümünden bağlantıyı hemen kesin.' },
    SYSTEM_MCP_APPROVAL_PENDING: { title: 'Yapay zekâ işlemi onayınızı bekliyor', body: '"{clientName}" bir işlem öneriyor: {title}. İşlem siz onaylayana kadar YAPILMAZ; ayrıntıları inceleyip onaylayın ya da reddedin (10 dakika içinde).' },
    SYSTEM_ANNOUNCEMENT: { title: 'Duyuru', body: 'Yeni bir duyuru yayınlandı. Ayrıntılar için açın.' },
    PLATFORM_ALERT_FIRING: { title: 'Platform uyarısı', body: '{ruleId} kuralı tetiklendi (uyarı: {alertId}).' },
    PLATFORM_ALERT_RESOLVED: { title: 'Platform uyarısı çözüldü', body: '{ruleId} kuralı normale döndü (uyarı: {alertId}).' },
    PLATFORM_ALERT_DIGEST: { title: 'Platform uyarı özeti', body: '{newAlertCount} yeni uyarı oluştu.' },
    PLATFORM_DELIVERY_DEAD_LETTERS: { title: 'Teslim edilemeyen bildirimler', body: 'Son saatte {deadCount} teslim kalıcı olarak başarısız oldu.' },
    PLATFORM_COMPLIANCE_FINDING: { title: 'Uyumluluk bulgusu', body: '{integ} için yeni bir bulgu var (kayıt: {findingId}).' },
};
